openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/events/push:
    post:
      tags:
      - events-controller
      operationId: pushEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PushEventRequest"
        required: true
      responses:
        "200":
          description: OK
  /api/v1/chats/{chatId}/messages:
    post:
      tags:
      - chats-controller
      operationId: sendMessage
      parameters:
      - name: chatId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
        required: true
      responses:
        "200":
          description: OK
  /api/v1/chats/{chatId}/members/{userId}:
    get:
      tags:
      - chats-controller
      operationId: userInChat
      parameters:
      - name: chatId
        in: path
        required: true
        schema:
          type: string
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChatMemberResponse"
  /api/v1/identity/resolve:
    post:
      tags:
      - identity-controller
      operationId: resolve
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mxid:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  internal_uuid:
                    type: string
                    format: uuid
                  created:
                    type: boolean
        "400":
          description: invalid_mxid
  /api/v1/identity/resolve-batch:
    post:
      tags:
      - identity-controller
      operationId: resolveBatch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mxids:
                  type: array
                  items:
                    type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  map:
                    type: object
                    additionalProperties:
                      type: string
                      format: uuid
        "400":
          description: invalid_mxid
  /api/v1/identity/lookup-batch:
    post:
      tags:
      - identity-controller
      operationId: lookupBatch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                uuids:
                  type: array
                  items:
                    type: string
                    format: uuid
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  map:
                    type: object
                    additionalProperties:
                      type: string
  /api/v1/identity/{internalUuid}:
    get:
      tags:
      - identity-controller
      operationId: lookup
      parameters:
      - name: internalUuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  mxid:
                    type: string
        "404":
          description: unknown_user
components:
  schemas:
    PushEventRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        pluginId:
          type: string
          format: uuid
        chatId:
          type: string
        eventName:
          type: string
        eventData:
          type: object
          additionalProperties:
            type: object
    SendMessageRequest:
      type: object
      properties:
        pluginSenderId:
          type: string
          format: uuid
        message:
          type: string
    ChatMemberResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        role:
          type: string
          enum:
          - REGULAR
          - ADMIN
        member:
          type: boolean
