spring.application.name=Fstick registry service
spring.jackson.property-naming-strategy=SNAKE_CASE

minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=11111111
minio.bucket=f-stick-plugins