spring.application.name=Fstick registry service
spring.jackson.property-naming-strategy=SNAKE_CASE

minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:11111111}
minio.bucket=${MINIO_BUCKET:f-stick-plugins}
minio.public-url=${MINIO_PUBLIC_URL:http://localhost:9010}
minio.internal-url=${MINIO_INTERNAL_URL:http://minio:9010}

spring.datasource.url=jdbc:postgresql://localhost:5432/registry_service
spring.datasource.username=admin
spring.datasource.password=1

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
debug=true