spring.application.name=Fstick registry service
spring.jackson.property-naming-strategy=SNAKE_CASE

minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=11111111
minio.bucket=f-stick-plugins

spring.datasource.url=jdbc:postgresql://localhost:5432/registry_service
spring.datasource.username=admin
spring.datasource.password=1

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
debug=true