spring.application.name=installation-service

spring.datasource.url=jdbc:postgresql://localhost:5433/installation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081