spring.application.name=runtime-service
spring.jackson.property-naming-strategy=SNAKE_CASE

integration.service.url=${INTEGRATION_SERVICE_URL:http://localhost:8080}
registry.service.url=${REGISTRY_SERVICE_URL:http://localhost:8082}
