services:
    postgres:
        image: postgres:16
        container_name: plugins-db
        restart: always

        environment:
            POSTGRES_DB: registry_service
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1

        ports:
            - "5434:5432"

        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d

volumes:
    pgdata: