services:
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: 11111111
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
    

volumes:
    minio_data:
