openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/v1/plugins/{pluginId}:
    get:
      tags:
        - plugins-controller
      operationId: getPlugin
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PluginViewExtend"
    put:
      tags:
        - plugins-controller
      operationId: updatePlugin
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PluginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PluginViewExtend"
    delete:
      tags:
        - plugins-controller
      operationId: deletePlugin
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChangeStatusResponse"
  /api/v1/plugins/{pluginId}/status:
    put:
      tags:
        - plugins-controller
      operationId: changeStatus
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: string
              enum:
                - ACTIVE
                - DELETED
                - HIDDEN
                - ARCHIVED
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChangeStatusResponse"
  /api/v1/plugins:
    get:
      tags:
        - plugins-controller
      operationId: getPlugins
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 20
        - name: category
          in: query
          required: false
          schema:
            type: string
            default: ""
        - name: search
          in: query
          required: false
          schema:
            type: string
            default: ""
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: name
        - name: order
          in: query
          required: false
          schema:
            type: string
            default: asc
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PluginsView"
    post:
      tags:
        - plugins-controller
      operationId: addPlugin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPluginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddPluginResponse"
  /api/v1/plugins/{pluginId}/versions:
    post:
      tags:
        - plugins-controller
      operationId: addPluginVersion
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPluginVersionRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AddVersionResponse"
  /api/v1/plugins/{pluginId}/versions/commit:
    post:
      tags:
        - plugins-controller
      operationId: commitVersion
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommitVersionRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PluginViewExtend"
  /api/v1/plugins/{pluginId}/commit:
    post:
      tags:
        - plugins-controller
      operationId: commitPlugin
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommitPluginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PluginViewExtend"
  /api/v1/plugins/{pluginId}/assets:
    post:
      tags:
        - plugins-controller
      operationId: updateAssets
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAssetsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UpdateAssetsResponse"
  /api/v1/plugins/{pluginId}/assets/commit:
    post:
      tags:
        - plugins-controller
      operationId: commitAssets
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommitAssetsRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PluginViewExtend"
  /api/v1/plugins/{pluginId}/code/server:
    get:
      tags:
        - plugins-controller
      operationId: getPluginCodeServer
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: version
          in: query
          required: true
          schema:
            type: string
        - name: runtime
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CodeLinksResponse"
  /api/v1/plugins/{pluginId}/code/client:
    get:
      tags:
        - plugins-controller
      operationId: getPluginCodeClient
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: version
          in: query
          required: true
          schema:
            type: string
        - name: runtime
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CodeLinksResponse"
  /api/v1/plugins/{pluginId}/assets/{assetId}:
    delete:
      tags:
        - plugins-controller
      operationId: deleteAssets
      parameters:
        - name: pluginId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: assetId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
components:
  schemas:
    PluginRequest:
      required:
        - description
        - name
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
    PluginViewExtend:
      type: object
      properties:
        id:
          type: string
          format: uuid
        authorId:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
        iconUrl:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        versions:
          type: array
          items:
            $ref: "#/components/schemas/VersionView"
        screenshots:
          type: array
          items:
            $ref: "#/components/schemas/ScreenshotView"
    ScreenshotView:
      type: object
      properties:
        screenshotId:
          type: string
          format: uuid
        screenshotUrl:
          type: string
    VersionView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        version:
          type: string
        changelog:
          type: string
        createdAt:
          type: string
    ChangeStatusResponse:
      type: object
      properties:
        pluginId:
          type: string
          format: uuid
        newStatus:
          type: string
        oldStatus:
          type: string
    AddPluginRequest:
      type: object
      properties:
        version:
          type: string
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileRequest"
        icon:
          $ref: "#/components/schemas/FileRequest"
    FileRequest:
      type: object
      properties:
        fileName:
          type: string
        type:
          type: string
    AddPluginResponse:
      type: object
      properties:
        pluginId:
          type: string
          format: uuid
        uploads:
          type: array
          items:
            $ref: "#/components/schemas/FileUploadData"
        iconUpload:
          $ref: "#/components/schemas/FileUploadData"
    FileUploadData:
      type: object
      properties:
        fileName:
          type: string
        key:
          type: string
        uploadUrl:
          type: string
    AddPluginVersionRequest:
      type: object
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileRequest"
        version:
          type: string
    AddVersionResponse:
      type: object
      properties:
        pluginId:
          type: string
          format: uuid
        versionId:
          type: string
          format: uuid
        uploads:
          type: array
          items:
            $ref: "#/components/schemas/FileUploadData"
    CommitVersionRequest:
      type: object
      properties:
        version:
          type: string
        changelog:
          type: string
        keys:
          type: array
          items:
            type: string
    CommitPluginRequest:
      required:
        - authorId
        - description
        - name
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        authorId:
          type: string
          format: uuid
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        keys:
          type: array
          items:
            type: string
    UpdateAssetsRequest:
      type: object
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileRequest"
    UpdateAssetsResponse:
      type: object
      properties:
        pluginId:
          type: string
          format: uuid
        uploads:
          type: array
          items:
            $ref: "#/components/schemas/FileUploadData"
    CommitAssetsRequest:
      type: object
      properties:
        keys:
          type: array
          items:
            type: string
    PaginationData:
      type: object
      properties:
        page:
          type: integer
          format: int32
        limit:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        hasPrev:
          type: boolean
        hasNext:
          type: boolean
    PluginViewShrink:
      type: object
      properties:
        id:
          type: string
          format: uuid
        authorId:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        status:
          type: string
        iconUrl:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    PluginsView:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/PluginViewShrink"
        pagination:
          $ref: "#/components/schemas/PaginationData"
    CodeLinksResponse:
      type: object
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileDownloadData"
    FileDownloadData:
      type: object
      properties:
        downloadUrl:
          type: string
